[env:esp01]
platform = espressif8266
board = esp01
framework = arduino
monitor_speed = 115200

; [env:d1_mini]
; platform = espressif8266
; board = d1_mini
; framework = arduino
; monitor_speed = 115200

; lib_deps = 
;     d:/Arduino/libraries/LibPrintf
;     d:/Arduino/libraries/GyverTimer
;     d:/Arduino/libraries/LedBlink


