[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
lib_deps = 
    d:/Arduino/libraries/GyverTimer
    d:/Arduino/libraries/LedBlink

