[env:d1_mini]
platform = espressif8266
board = d1_mini
framework = arduino
monitor_speed = 115200
lib_deps = 
    d:/Arduino/libraries/LibPrintf
    d:/Arduino/libraries/GyverTimer
    d:/Arduino/libraries/LedBlink
    d:/Arduino/libraries/PubSubClient
    d:/Arduino/libraries/ESPWebServer
    d:/Arduino/libraries/ESPping
    d:/Arduino/libraries/ESP/ESP8266WiFi
    d:/Arduino/libraries/ESP/EEPROM



