
[env:d1_mini]
platform = espressif8266
board = d1_mini
framework = arduino
monitor_speed = 115200
upload_speed = 460800

lib_deps = 
    ; d:/Arduino/libraries/LibPrintf
    ; d:/Arduino/libraries/GyverTimer
    ; d:/Arduino/libraries/LedBlink
    ; d:/Arduino/libraries/IRremoteESP8266
    d:/Arduino/libraries/FastLED