#define RECV_PIN 2
#define RED_LED_PIN 4
#define PIR_PIN A1

#define LIGHT_PIN 6
#define LIGHT_ON_TIME 5000
#define GROUND_PIN 7

#define BEEP_SIGNAL_PIN 10
#define BEEP_GROUND_PIN 12
#define BEEP_POWER_PIN 11

#define SOUND_SENSOR_PIN A0
#define SOUND_SENSOR_GROUND_PIN 8
#define SOUND_SENSOR_POWER_PIN 9
#define SOUND_CHECK_INTERVAL 1000